# Generated by Django 4.2.4 on 2023-11-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción del producto')),
                ('precio', models.IntegerField(verbose_name='Precio del producto')),
                ('talla', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=2, verbose_name='Talla del producto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Productos/', verbose_name='Imagen del producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
            },
        ),
    ]
