# Generated by Django 4.2.4 on 2023-11-26 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teslo_shop', '0003_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
