# Generated by Django 4.2.4 on 2023-11-27 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teslo_shop', '0004_delete_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código de venta')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('nombre_comprador', models.CharField(max_length=100, verbose_name='Nombre del comprador')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de venta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teslo_shop.producto')),
            ],
        ),
    ]
